// packages/collector-server/src/leadership/aggregator.ts
// Composes all 32 signal computers into OverviewSnapshot / MemberDetail / ProjectDetail.

import {
  scanAllSessions,
  isNoiseProjectName,
  resolveProjectIdentity,
  propagateRemotes,
} from './transcript-loader.js';
import type {
  ParsedSession,
  OverviewSnapshot,
  MemberSnapshot,
  MemberDetail,
  MemberStateBadge,
  ProjectSnapshot,
  ProjectDetail,
  CollabHit,
  KpiCards,
  SessionSummary,
  DateRange,
  AttentionItem,
  HighlightEvent,
} from './types.js';
import { redactForLLM } from './llm/redact.js';
import { computeActivity, computeFocus, computeRhythmDelta } from './signals/activity.js';
import { detectLowActivity } from './signals/slacking.js';
import { detectBlocker } from './signals/blockers.js';
import { detectHelpNeeded } from './signals/help-needed.js';
import { detectCollabHits } from './signals/collaboration.js';
import {
  computeToolFailureRate,
  countContextOverflow,
  computeIterationDensity,
  promptLengthSeries,
} from './signals/quality.js';
import { extractRiskyActions, sumRedactions } from './signals/risk.js';
import { computeCostUsd, computeModelMix } from './signals/cost.js';
import { computeWebResearch, computeNewSurfaceCount } from './signals/learning.js';
import { classifyProject, getRecentFiles } from './signals/project-status.js';
import { projectEta } from './signals/project-eta.js';
import {
  computeCollabDensity,
  computeContributors,
  hasBusFactorWarning,
} from './signals/project-collab.js';
import { computeExtensionMix, computeTestRatio } from './signals/project-stack.js';
import { guessPhase } from './signals/project-phase.js';
import { computeHealthScore, extractMilestones } from './signals/project-health.js';
import { computeWebResearchShare, computeTrend7d, computeHeatmap7x24 } from './signals/project-rhythm.js';
import type { LlmCache } from './llm/cache.js';
import type {
  T1Input,
  T2Input,
  T3Input,
  T4Input,
  T5Input,
} from './llm/prompts/index.js';
import {
  t1CacheKey,
  t2CacheKey,
  t3CacheKey,
  t4CacheKey,
  t5CacheKey,
} from './llm/cache-keys.js';

// sumRedactions is imported but only used indirectly (available for callers).
// Suppress TS unused-import by using it in a re-export.
export { sumRedactions };

// 2026-05-18 round-16 audit P0: "prompt 的演变" was showing slash-command
// injections (<command-message>, <command-name>) and skill auto-load text
// ("Base directory for this skill: …") instead of real user input. These come
// through as role=user, content=string in the raw .jsonl (Claude Code injects
// them as if the user typed them), so the parser correctly keeps them — but
// for the leadership view they are noise. Filter them at the aggregator so
// the drawer's "看他都在问什么" only shows what the user actually typed.
function isSystemInjectedUserMessage(text: string): boolean {
  const t = text.trimStart();
  if (!t) return true;
  // Claude Code wraps slash command / hook / IDE / skill injections in
  // angle-bracket tags. Detect the leading tag prefix generically so we don't
  // have to enumerate every variant (<task-notification>, <ide_selection>,
  // <user-prompt-submit-hook>, …). The first 60 chars are enough: real human
  // prompts almost never start with a tag-shaped token followed by content.
  if (/^<[a-z][a-z0-9_-]*[\s>]/i.test(t.slice(0, 60))) return true;
  // Non-tag system injections.
  if (t.startsWith('Caveat: The messages below were generated by the user while running local commands')) return true;
  if (t.startsWith('Base directory for this skill:')) return true;
  if (t.startsWith('Stop hook feedback:') || t.startsWith('PreToolUse hook feedback:') || t.startsWith('PostToolUse hook feedback:')) return true;
  return false;
}

export interface BuildOverviewInput {
  collectorDir: string;
  range: DateRange;
  now: Date;
  /** Project names treated as "main" for slacking detection. Empty array disables that check. */
  mainProjects?: string[];
  /** Test seam — inject sessions instead of disk scan. */
  sessions?: ParsedSession[];
  /**
   * Optional LLM narrative enrichment. When provided, the aggregator reads
   * cached T1–T5 outputs and attaches them to the snapshot's `llm*` fields.
   * The LLM is NEVER called from this path — the worker (L-9) fills the
   * cache asynchronously. Absent → behaviour identical to pre-L-8.
   */
  llmCache?: LlmCache;
  /** ISO date string (YYYY-MM-DD) used for the T5 cache key. Defaults to today. */
  today?: string;
}

export function buildOverviewSnapshot(input: BuildOverviewInput): OverviewSnapshot {
  const sessions = input.sessions ?? loadSessionsForRange(input.collectorDir, input.range);
  // When sessions were injected (test seam) the disk scan's propagation
  // pass never ran. Re-run it idempotently so test fixtures that set
  // `envelope.gitRemote` on a subset still flow to the cwd-sibling
  // sessions. Disk-loaded sessions had this done in `scanAllSessions`;
  // running it again is a no-op there.
  if (input.sessions) propagateRemotes(sessions);
  const inRange = sessions.filter((s) => s.startTs >= input.range.start && s.startTs <= input.range.end);

  const teamMedianTokens = median(inRange.map((s) => s.tokens.input + s.tokens.output));

  // Members
  const byEmail = groupBy(inRange, (s) => s.envelope.userId);
  const memberEmails = [...byEmail.keys()].sort();
  const members: MemberSnapshot[] = memberEmails.map((email) =>
    buildMemberSnapshotInner(email, byEmail.get(email) ?? [], inRange, teamMedianTokens, input),
  );

  // Second pass — reclassify stateBadge against team distribution (P-D2).
  // Absolute thresholds (e.g. failRate > 0.2) and the bare-keyword detector
  // both flagged ~all members on the real 2026-05-14 snapshot — `help`,
  // `stuck`, `卡住` are common substrings in any technical conversation.
  // Relative percentile gates make the badge mean "high vs team", which is
  // the only useful signal at small team sizes. `stuck` is preserved when
  // the structural blocker detector fired (3 sessions same cwd, no commit).
  reclassifyMemberStateAgainstTeam(members, byEmail);

  // Projects — filter noise + low-volume scratch BEFORE finalizing list (P-D2).
  // We compute raw snapshots over all groups, then apply the noise filter and
  // the < 3-session cutoff with an optional env allow-list escape hatch.
  // Group by `resolveProjectIdentity` so any session that learned its github
  // remote at parse time (or via cwd-prefix propagation) collapses with its
  // siblings under one `owner/repo` key instead of fragmenting across the
  // multiple cwd-derived names.
  const byProject = groupBy(inRange, (s) => resolveProjectIdentity(s.envelope));
  const projectNames = [...byProject.keys()].sort();
  const allowList = parseProjectAllowList(process.env.LEADERSHIP_PROJECT_ALLOW);
  const projects: ProjectSnapshot[] = projectNames
    .map((name) => buildProjectSnapshotInner(name, byProject.get(name) ?? [], input.now))
    .filter((p) => isProjectInteresting(p, allowList));

  // Collaboration
  const collaboration: CollabHit[] = detectCollabHits(inRange);

  // Attention items (P-B4) — derived from member badges + project signals,
  // sorted by severity desc, folded by shape, and globally capped (P-D2).
  const attention: AttentionItem[] = deriveAttention(members, projects, input.now, byProject, byEmail);

  // Team-wide pace: today vs prior-7-day daily-average tokens.
  // Uses the same computeRhythmDelta helper that powers per-member delta,
  // but applied to the whole team so the dashboard card reflects real motion.
  const sevenDayWindowStart = new Date(input.now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const todayTeamSessions = filterToday(inRange, input.now);
  const past7TeamSessions = inRange.filter((s) => s.startTs < sevenDayWindowStart);
  const rhythmDelta = computeRhythmDelta(todayTeamSessions, past7TeamSessions);
  const paceLabel: '升' | '稳' | '缓' =
    rhythmDelta > 0.2 ? '升' : rhythmDelta < -0.2 ? '缓' : '稳';

  // High-output members + their mean delta — replaces hardcoded "↑" trend line.
  const highOutputMembers = members.filter((m) => m.deltaVs7dAvgPct > 0.2);
  const avgHighOutputDelta = highOutputMembers.length === 0
    ? 0
    : highOutputMembers.reduce((a, m) => a + m.deltaVs7dAvgPct, 0) / highOutputMembers.length;

  // Today $ cost — sum across all members' today.costUsd
  const todayCostUsd = members.reduce((a, m) => a + (m?.today?.costUsd ?? 0), 0);

  // KPI cards
  const stuckCount = members.filter((m) => m.stateBadge === 'stuck').length;
  const helpCount = members.filter((m) => m.stateBadge === 'needs_help').length;
  const riskyCount = members.filter((m) => m.warnings.some((w) => /危险|risky/i.test(w))).length;
  const kpis: KpiCards = {
    teamActivity: { value: inRange.length, deltaVsAvg: 0 },
    attention: {
      value: stuckCount + helpCount + riskyCount,
      deltaToday: 0,
      breakdown: { stuck: stuckCount, needsHelp: helpCount, riskyAction: riskyCount },
    },
    projects: {
      active: projects.filter((p) => p.state === 'active').length,
      maintaining: projects.filter((p) => p.state === 'maintaining').length,
      dormant: projects.filter((p) => p.state === 'dormant').length,
    },
    pace: { rhythmDelta, label: paceLabel },
    highOutput: { count: highOutputMembers.length, avgDeltaPct: avgHighOutputDelta },
    todayCostUsd: Math.round(todayCostUsd * 100) / 100,
  };

  // Snapshot staleness — when the freshest session in `inRange` is older than
  // 1 day relative to `now`, surface a banner-ready signal so the renderer
  // can warn the leader that "today" KPIs are relative to a stale capture
  // rather than live data. Computed AFTER the filter passes so we use the
  // same session set the dashboard renders.
  const staleness = computeStaleness(inRange, input.now);

  // "本周关键进展" (B-main, new section A) — aggregate milestones across
  // every surviving project's sessions within the trailing 7-day window so
  // the Overview can surface a single editorial feed of commits / pushes /
  // PRs without per-project drill-down. ProjectSnapshot doesn't carry the
  // milestones list (those live on ProjectDetail), so we run the same
  // extractor used by buildProjectDetail directly on the per-project
  // session groups. Author emails are normalised to local-part here so the
  // renderer never sees a full address.
  const weekAgo = input.now.getTime() - 7 * 24 * 60 * 60 * 1000;
  const highlights: HighlightEvent[] = [];
  for (const p of projects) {
    const psess = byProject.get(p.name) ?? [];
    if (psess.length === 0) continue;
    const milestones = extractMilestones(psess);
    for (const m of milestones) {
      const tsMs = Date.parse(m.ts);
      if (!Number.isFinite(tsMs) || tsMs < weekAgo) continue;
      highlights.push({
        ts: m.ts,
        type: m.type,
        by: localPart(m.by),
        project: p.name,
        // Redact at aggregator time so both wire JSON and rendered HTML see
        // the safe version. Highlight details are raw Bash tool inputs
        // (`git push origin foo 2>&1 | tail -5`, `cd /Users/alice/...`); the
        // PII redactor strips absolute paths / emails / secrets, and we
        // hard-cap length at 120 chars (the renderer further trims to 80).
        detail: redactHighlightDetail(m.detail),
      });
    }
  }
  highlights.sort((a, b) => b.ts.localeCompare(a.ts));
  const highlightsTop = highlights.slice(0, 10);

  const snap: OverviewSnapshot = {
    schemaVersion: 1,
    range: {
      start: input.range.start.toISOString(),
      end: input.range.end.toISOString(),
      label: String(input.range.label),
    },
    computedAt: input.now.toISOString(),
    kpis,
    members,
    projects,
    collaboration,
    attention,
    highlights: highlightsTop,
  };
  if (staleness) snap.staleness = staleness;

  // L-8: attach LLM narrative fields from the cache when a cache is provided.
  // Cache-only path — never calls the LLM here. Worker (L-9) fills the cache
  // asynchronously; we just read whatever is already there.
  if (input.llmCache) {
    attachLlmFields(snap, inRange, byEmail, byProject, input);
  }

  return snap;
}

// ---------------------------------------------------------------------------
// L-8 — LLM narrative enrichment (cache-only, synchronous)
// ---------------------------------------------------------------------------

/**
 * Read T1–T5 cached outputs for this snapshot and attach them to the matching
 * snapshot entities. **Never calls the LLM** — we recompute the cache keys
 * deterministically from snapshot data (mirroring `llm/summarizer.ts`) and do
 * pure `Map.get` lookups against the in-memory cache. Misses leave the
 * corresponding `llm*` field undefined so the renderer falls back to its
 * template strings.
 *
 * Why duplicate the key shapes from summarizer.ts instead of calling
 * `summarizeXxx(..., {cacheOnly: true})` directly? Those functions are typed
 * async and `Promise.resolve` cannot be unwrapped synchronously — keeping
 * `buildOverviewSnapshot` synchronous lets the existing `routes.ts` handlers
 * stay synchronous too. The key shapes are stable by design (worker writes
 * by them; aggregator reads by them) and small enough that duplication is
 * cheaper than refactoring the whole HTTP pipeline to async.
 */
function attachLlmFields(
  snap: OverviewSnapshot,
  inRange: ParsedSession[],
  byEmail: Map<string, ParsedSession[]>,
  byProject: Map<string, ParsedSession[]>,
  input: BuildOverviewInput,
): void {
  const cache = input.llmCache;
  if (!cache) return;

  // --- T1: session digests across the whole range ----------------------------
  const sessionsMap = new Map<string, string>();
  const t1Inputs: T1Input[] = [];
  for (const s of inRange) {
    const t1 = buildT1InputFromSession(s);
    if (!t1) continue;
    t1Inputs.push(t1);
    const v = cache.get(t1CacheKey(t1));
    if (v !== undefined) sessionsMap.set(t1.id, v);
  }

  // --- T2: per-member weekly digest ------------------------------------------
  const membersMap = new Map<string, string>();
  for (const m of snap.members) {
    if (!m.email) continue;
    const memSessions = byEmail.get(m.email) ?? [];
    const t2 = buildT2InputForMember(m, memSessions, sessionsMap);
    if (!t2) continue;
    const v = cache.get(t2CacheKey(t2));
    if (v !== undefined) {
      membersMap.set(m.email, v);
      m.llmWeekly = v;
    }
  }

  // --- T3: per-project weekly digest -----------------------------------------
  const projectsMap = new Map<string, string>();
  for (const p of snap.projects) {
    if (!p.name) continue;
    const psess = byProject.get(p.name) ?? [];
    const t3 = buildT3InputForProject(p, psess, sessionsMap);
    if (!t3) continue;
    const v = cache.get(t3CacheKey(t3));
    if (v !== undefined) {
      projectsMap.set(p.name, v);
      p.llmWeekly = v;
    }
  }

  // --- T4: attention rewrites ------------------------------------------------
  const attentionMap = new Map<string, string>();
  for (const it of snap.attention) {
    const t4 = buildT4InputForAttention(it);
    if (!t4) continue;
    const v = cache.get(t4CacheKey(t4));
    if (v !== undefined) {
      attentionMap.set(it.refId, v);
      it.llmRewrite = v;
    }
  }

  // --- T1 → highlight digests -----------------------------------------------
  // HighlightEvent has no sessionId field today; we key T1 by sessionId in the
  // cache. Walk each highlight's project's session bucket and find the session
  // whose [startTs, endTs] window contains the highlight.ts (best effort).
  for (const h of snap.highlights) {
    const sid = findSessionIdForHighlight(h, byProject);
    if (!sid) continue;
    const v = sessionsMap.get(sid);
    if (v !== undefined) h.llmDigest = v;
  }

  // --- T5: daily leader brief ------------------------------------------------
  // Render path uses the populated maps — sessionsMap (T1), projectsMap (T3),
  // and the T4 rewrites we just collected. The worker side stays aligned via
  // `WorkerInputs.rebuildBrief`, which re-reads the same tiers from cache
  // after T1/T3/T4 fill, so both sides hash the same T5Input and the cache
  // key collides.
  const today = input.today ?? new Date().toISOString().slice(0, 10);
  const t5Input: T5Input = buildT5InputFromSnapshot(
    snap,
    byProject,
    sessionsMap,
    projectsMap,
    [...attentionMap.values()],
    today,
  );
  const briefRaw = cache.get(t5CacheKey(t5Input));
  if (briefRaw !== undefined) {
    try {
      const arr = JSON.parse(briefRaw);
      if (Array.isArray(arr) && arr.every((x) => typeof x === 'string') && arr.length > 0) {
        snap.llmBrief = arr as string[];
      }
    } catch {
      // Malformed cache value — silently skip so the template fallback renders.
    }
  }
}

/**
 * Build a T1 input from a parsed session. Mirrors the data the worker (L-9)
 * will pack; key shape MUST match exactly so cache lookups hit.
 *
 * Exported so the worker's input collector (`llm/inputs.ts`) can reuse the
 * exact same packing — the aggregator-render and worker-fill paths MUST
 * produce identical T1 inputs for the cache to deduplicate.
 */
export function buildT1InputFromSession(s: ParsedSession): T1Input | null {
  const id = s.envelope.sessionId;
  if (!id) return null;

  // First user message text, ≤200 chars
  let firstUserPrompt = '';
  for (const m of s.messages) {
    if (m.role === 'user' && m.text.trim().length > 0 && !isSystemInjectedUserMessage(m.text)) {
      firstUserPrompt = m.text.length > 200 ? m.text.slice(0, 200) : m.text;
      break;
    }
  }

  // Up to 3 distinct edited file paths
  const filesSeen = new Set<string>();
  const changedFiles: string[] = [];
  for (const m of s.messages) {
    for (const tu of m.toolUses) {
      if (tu.name === 'Edit' || tu.name === 'Write' || tu.name === 'MultiEdit') {
        const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
        if (fp && !filesSeen.has(fp)) {
          filesSeen.add(fp);
          changedFiles.push(fp);
          if (changedFiles.length >= 3) break;
        }
      }
    }
    if (changedFiles.length >= 3) break;
  }

  // Tool counts + errors
  let edit = 0;
  let bash = 0;
  let read = 0;
  let webFetch = 0;
  let errors = 0;
  for (const m of s.messages) {
    for (const tu of m.toolUses) {
      if (tu.name === 'Edit' || tu.name === 'Write' || tu.name === 'MultiEdit') edit++;
      else if (tu.name === 'Bash') bash++;
      else if (tu.name === 'Read') read++;
      else if (tu.name === 'WebFetch' || tu.name === 'WebSearch') webFetch++;
    }
    for (const tr of m.toolResults) {
      if (tr.isError) errors++;
    }
  }

  const durationMin = Math.max(0, Math.round(s.durationMs / 60_000));
  return {
    id,
    firstUserPrompt,
    changedFiles,
    toolCounts: { edit, bash, read, webFetch },
    durationMin,
    errors,
  };
}

/**
 * Build a T2 input for one member from their week's sessions. `sessionsMap`
 * maps `sessionId` → T1 digest so the prompt can include the member's
 * already-cached session lines. Exported for `llm/inputs.ts`.
 */
export function buildT2InputForMember(
  m: MemberSnapshot,
  memberSessions: ParsedSession[],
  sessionsMap: Map<string, string>,
): T2Input | null {
  if (!m.email) return null;
  const topFiles = computeTopFiles(memberSessions, 5);
  const sessionDigests: string[] = [];
  for (const s of memberSessions) {
    const v = sessionsMap.get(s.envelope.sessionId);
    if (v) sessionDigests.push(v);
  }
  return {
    email: m.email,
    displayName: m.displayName,
    state: mapStateBadgeToT2(m.stateBadge),
    topFiles,
    sessionDigests,
  };
}

/**
 * Build a T3 input for one project. `sessionsMap` is the same T1 digest map
 * used by `buildT2InputForMember`. Exported for `llm/inputs.ts`.
 */
export function buildT3InputForProject(
  p: ProjectSnapshot,
  projectSessions: ParsedSession[],
  sessionsMap: Map<string, string>,
): T3Input | null {
  if (!p.name) return null;
  const sessionDigests: string[] = [];
  for (const s of projectSessions) {
    const v = sessionsMap.get(s.envelope.sessionId);
    if (v) sessionDigests.push(v);
  }
  return {
    project: p.name,
    phase: p.phaseGuess ?? '',
    contributors: p.contributors.map((c) => localPart(c.email)),
    sessionDigests,
    recentCommits: [],
  };
}

/**
 * Build a T4 input from one attention item. Strips HTML wrapping tags from
 * `line2` so the redactor only sees plain text. Exported for `llm/inputs.ts`.
 */
export function buildT4InputForAttention(it: AttentionItem): T4Input | null {
  if (!it.refId) return null;
  // Strip HTML tags from line2 — attention.line2 may contain `<span class="mono">`.
  const evidence = it.line2 ? [it.line2.replace(/<[^>]+>/g, '')] : [];
  return {
    refId: it.refId,
    kind: it.kind,
    displayName: it.displayName,
    signal: it.tag,
    evidence,
  };
}

/**
 * Build a T5 daily-brief input from the snapshot plus the per-session and
 * per-project T1/T3 digest maps. Exported so `llm/inputs.ts` can construct
 * the same shape the aggregator reads — key MUST match for the cache to hit.
 *
 * `attentionRewrites` is passed in (rather than derived from `snap.attention`)
 * because the aggregator already computed it during its T4 cache lookups; the
 * worker path passes whatever T4 outputs it just summarised.
 */
export function buildT5InputFromSnapshot(
  snap: OverviewSnapshot,
  byProject: Map<string, ParsedSession[]>,
  sessionsMap: Map<string, string>,
  projectsMap: Map<string, string>,
  attentionRewrites: string[],
  today: string,
): T5Input {
  return {
    date: today,
    topHighlights: snap.highlights.slice(0, 5).map((h) => {
      const sid = findSessionIdForHighlight(h, byProject);
      const fromT1 = sid ? sessionsMap.get(sid) : undefined;
      return fromT1 ?? h.detail.slice(0, 80);
    }),
    attentionRewrites,
    topProjects: snap.projects.slice(0, 3).map((p) => ({
      name: p.name,
      digest: projectsMap.get(p.name) ?? '',
    })),
  };
}

/** Map MemberStateBadge → T2Input.state (the prompt-tier's state enum). */
function mapStateBadgeToT2(badge: MemberStateBadge): T2Input['state'] {
  switch (badge) {
    case 'needs_help': return 'needs_help';
    case 'stuck':      return 'stuck';
    case 'active':     return 'active';
    case 'low_activity': return 'idle';
    case 'quiet':      return 'off';
    default:           return 'active';
  }
}

/** Top-N edited files for a member's session bucket. */
function computeTopFiles(memberSessions: ParsedSession[], n: number): string[] {
  const counts = new Map<string, number>();
  for (const s of memberSessions) {
    for (const m of s.messages) {
      for (const tu of m.toolUses) {
        if (tu.name === 'Edit' || tu.name === 'Write' || tu.name === 'MultiEdit') {
          const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
          if (fp) counts.set(fp, (counts.get(fp) ?? 0) + 1);
        }
      }
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([path]) => path);
}

/**
 * Best-effort lookup of the sessionId for a given highlight. HighlightEvent
 * lacks a sessionId field, so we walk the highlight's project's session
 * bucket and pick the session whose startTs is the latest one ≤ the
 * highlight's ts (milestones are emitted with their message ts, which falls
 * inside the session's [startTs, endTs] window).
 */
function findSessionIdForHighlight(
  h: HighlightEvent,
  byProject: Map<string, ParsedSession[]>,
): string | undefined {
  const candidates = byProject.get(h.project);
  if (!candidates || candidates.length === 0) return undefined;
  const tsMs = Date.parse(h.ts);
  if (!Number.isFinite(tsMs)) return undefined;
  let bestId: string | undefined;
  let bestStart = -Infinity;
  for (const s of candidates) {
    const startMs = s.startTs.getTime();
    const endMs = s.endTs.getTime();
    // Prefer sessions whose [startTs, endTs] window contains the ts.
    if (startMs <= tsMs && tsMs <= endMs) {
      return s.envelope.sessionId;
    }
    // Fallback: latest start ≤ ts.
    if (startMs <= tsMs && startMs > bestStart) {
      bestStart = startMs;
      bestId = s.envelope.sessionId;
    }
  }
  return bestId;
}

// ---------------------------------------------------------------------------
// Helpers added during the 2026-05-17 data-trust-layer rebuild (P-D2)
// ---------------------------------------------------------------------------

/**
 * Inclusive linear-rank percentile. Returns 0 for empty inputs so callers can
 * compose into Math.max(percentile(...), floor) without an `isFinite` guard.
 *
 * Why not interpolated: at typical team sizes (3-15 members) interpolation
 * adds noise without changing the threshold meaningfully; nearest-rank keeps
 * the floor-driven calibration intuitive.
 */
function percentile(values: number[], p: number): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const idx = Math.min(Math.floor(sorted.length * p), sorted.length - 1);
  return sorted[idx]!;
}

/**
 * Reclassify each member's `stateBadge` against the team's distribution
 * (P-D2). The original implementation used absolute thresholds (failRate
 * > 0.2, sessions === 0, etc.) which flagged 6 of 6 members on the real
 * 2026-05-14 snapshot because the whole team had high failure rates. The
 * relative gates below cap the population that can be flagged to roughly
 * the worst quartile, with a hard floor so a single outlier still trips
 * when the team is small but well-behaved.
 *
 * State priority is preserved: stuck > needs_help > low_activity > quiet >
 * active. `stuck` is left untouched because the blocker detector already uses
 * structural evidence (3 sessions in the same cwd with no commit) that is
 * NOT susceptible to the distribution problem.
 */
function reclassifyMemberStateAgainstTeam(
  members: MemberSnapshot[],
  byEmail: Map<string, ParsedSession[]>,
): void {
  if (members.length === 0) return;
  const failureRates = members.map((m) => m.toolFailureRate ?? 0).filter((x) => x > 0);
  const p75Failure = Math.max(percentile(failureRates, 0.75), 0.1);
  const iterDensities = members.map((m) => m.iterationDensity ?? 0).filter((x) => x > 0);
  const p75Iter = Math.max(percentile(iterDensities, 0.75), 2.5);
  const recents = members.map((m) => {
    const sessions = byEmail.get(m.email) ?? [];
    return sessions.length;
  });
  const p20Recent = percentile(recents, 0.2);

  for (const m of members) {
    // Preserve `stuck` — that uses structural cwd-grouped evidence
    // (3 same-cwd sessions, no commit), not distributional signals.
    if (m.stateBadge === 'stuck') continue;
    const fail = m.toolFailureRate ?? 0;
    const iter = m.iterationDensity ?? 0;
    const recent = (byEmail.get(m.email) ?? []).length;

    if (fail > 0 && fail > p75Failure) {
      m.stateBadge = 'needs_help';
      continue;
    }
    if (iter > 0 && iter > p75Iter) {
      m.stateBadge = 'stuck';
      continue;
    }
    if (recent <= p20Recent && recent < 3) {
      m.stateBadge = 'low_activity';
      continue;
    }
    // No relative red flag → demote prior absolute-threshold / bare-keyword
    // misfires to `active`. `quiet` only when truly zero sessions.
    m.stateBadge = recent === 0 ? 'quiet' : 'active';
  }
}

/**
 * Parse the `LEADERSHIP_PROJECT_ALLOW` env var into a set of project names
 * that bypass the noise + low-volume filters. Empty / unset → no escape
 * hatch (default). Comma-separated, leading / trailing whitespace trimmed.
 *
 * This is the documented escape hatch for cases where the noise heuristics
 * are too eager — set the env var on the server and the listed names come
 * back into the dashboard unconditionally.
 */
function parseProjectAllowList(raw: string | undefined): Set<string> {
  if (!raw) return new Set();
  return new Set(
    raw
      .split(',')
      .map((s) => s.trim())
      .filter((s) => s.length > 0),
  );
}

/**
 * Apply the project-list noise filter introduced 2026-05-17 (P-D2). A
 * project survives when:
 *   - its name is in the LEADERSHIP_PROJECT_ALLOW allow-list (escape hatch);
 *   OR
 *   - its name is not noise (hash, bench fixture, etc.) AND it has at least
 *     3 sessions over the 7-day window. The < 3 cutoff drops one-off
 *     scratch projects without obscuring real low-volume work.
 */
function isProjectInteresting(p: ProjectSnapshot, allowList: Set<string>): boolean {
  if (allowList.has(p.name)) return true;
  if (isNoiseProjectName(p.name)) return false;
  // Drop "project name == contributor's email local-part" — that's the
  // signature of a session that ran in `/home/<user>/` without a real
  // project folder. Treats those as personal scratch.
  if (projectNameLooksLikeUsername(p)) return false;
  const totalSessions = p.trend7d.reduce((a, b) => a + b, 0);
  if (totalSessions < 3) return false;
  // Additional volume gate (2026-05-17 calibration): a "real" project on
  // the dashboard either spans ≥ 2 active days OR has ≥ 5 sessions. One
  // afternoon of 3-4 sessions is usually scratch/exploration, not work
  // worth dashboard real estate. Allow-list bypass already returned above.
  const activeDays = p.trend7d.filter((n) => n > 0).length;
  if (activeDays < 2 && totalSessions < 5) return false;
  return true;
}

/**
 * Detects the "project name is just a username" case (`hrdai`, `zhangziyi`
 * on the 2026-05-14 snapshot). These come from sessions whose cwd was the
 * user's home folder rather than a real repo. Compare lowercase.
 */
function projectNameLooksLikeUsername(p: ProjectSnapshot): boolean {
  const nameLc = p.name.toLowerCase();
  for (const c of p.contributors) {
    const atIdx = c.email.indexOf('@');
    const localPart = atIdx >= 0 ? c.email.slice(0, atIdx).toLowerCase() : c.email.toLowerCase();
    if (nameLc === localPart) return true;
    // Hostname-style emails (`zhangziyi@zhangziyideMacBook-Air.local`):
    // strip trailing `de…` (CJK possessive in Hanyu Pinyin) and digits so
    // we catch the common `<name>deLaptop` machine-id format.
    if (nameLc === localPart.replace(/(de)?[A-Za-z0-9_-]+$/, '')) {
      // Only accept this fuzzy match if the head is non-trivially long.
      if (nameLc.length >= 4) return true;
    }
  }
  return false;
}

/**
 * Compute snapshot staleness — `null` when the most-recent session in scope
 * is within ~1 day of `now`. Otherwise return a structured payload the
 * renderer turns into a "data is N days old" banner.
 *
 * Day boundary uses 86_400_000 ms = 1 day (no DST math needed — both ends
 * are ms-since-epoch). `ageDays` is rounded to one decimal so the banner
 * reads cleanly ("距今 3.2 天").
 */
function computeStaleness(
  sessions: ParsedSession[],
  now: Date,
): { ageDays: number; lastActivityAt: string } | undefined {
  if (sessions.length === 0) return undefined;
  let lastTs = sessions[0]!.endTs.getTime();
  for (const s of sessions) {
    const t = s.endTs.getTime();
    if (t > lastTs) lastTs = t;
  }
  const ageMs = now.getTime() - lastTs;
  const ageDays = ageMs / 86_400_000;
  if (ageDays <= 1) return undefined;
  return {
    ageDays: Math.round(ageDays * 10) / 10,
    lastActivityAt: new Date(lastTs).toISOString(),
  };
}

/**
 * Derive an attention list from member badges + project signals.
 * Output is sorted by severity DESC so the editorial card renders the most
 * urgent rows first. line2 is leader-narrative — no raw percentages, token
 * counts, or technical jargon. We extract one real fact (a risky-action
 * pattern, the top file, hours-since-activity, etc.) and dress it in a
 * sentence the dashboard's non-technical reader can act on.
 *
 * Email values are escaped before embedding (the renderer emits line2
 * unescaped so callers can include inline `<span class="mono">`). Everything
 * else interpolated is a number or controlled string from `_leader-lang.ts`.
 */
function deriveAttention(
  members: MemberSnapshot[],
  projects: ProjectSnapshot[],
  now: Date,
  projectSessionsByName?: Map<string, ParsedSession[]>,
  memberSessionsByEmail?: Map<string, ParsedSession[]>,
): AttentionItem[] {
  const items: AttentionItem[] = [];

  // Format a "time ago" stamp from an ISO timestamp; never returns em-dash
  // so the attention row's right-column always gives the reader a real
  // recency signal. Falls back to "本周" when the timestamp is unknown.
  const timeAgo = (iso?: string): string => {
    if (!iso) return '本周';
    const last = new Date(iso);
    if (Number.isNaN(last.getTime())) return '本周';
    const hours = Math.max(0, (now.getTime() - last.getTime()) / 3_600_000);
    if (hours < 1) return '刚刚';
    if (hours < 24) return `${Math.floor(hours)}h 前`;
    const days = Math.floor(hours / 24);
    return days === 1 ? '昨日' : `${days}天前`;
  };
  const projectLatest = (projectName: string): string | undefined => {
    const sessions = projectSessionsByName?.get(projectName);
    if (!sessions || sessions.length === 0) return undefined;
    let latest = sessions[0]!.startTs;
    for (const s of sessions) if (s.startTs > latest) latest = s.startTs;
    return latest.toISOString();
  };

  for (const m of members) {
    const initials = m.displayName.slice(0, 2).toLowerCase();
    const memSessions = memberSessionsByEmail?.get(m.email) ?? [];
    if (m.stateBadge === 'stuck') {
      const topFile = topEditedFile(memSessions);
      const line2 = topFile
        ? `卡在 <span class="mono">${escapeHtmlEmail(shortFilePath(topFile))}</span>`
        : `反复尝试相似问题`;
      items.push({
        kind: 'member', refId: m.email, displayName: m.displayName, initials,
        tag: '疑似卡住', tagSeverity: 'urgent',
        line2,
        time: timeAgo(m.lastSessionAt), severity: 9,
      });
    }
    if (m.stateBadge === 'needs_help') {
      const topRisky = topRiskyPattern(memSessions);
      const line2 = topRisky
        ? `${riskyPatternLabel(topRisky)} 等高风险操作`
        : `Bash 命令反复受阻`;
      items.push({
        kind: 'member', refId: m.email, displayName: m.displayName, initials,
        tag: '求助', tagSeverity: 'urgent',
        line2,
        time: timeAgo(m.lastSessionAt), severity: 8,
      });
    }
    if (m.stateBadge === 'low_activity') {
      let line2 = `本周参与不多`;
      if (m.lastSessionAt) {
        const last = new Date(m.lastSessionAt);
        const idleHours = Math.max(0, (now.getTime() - last.getTime()) / 3_600_000);
        line2 = `${narrativeIdleSince(idleHours)}无新动作`;
      }
      items.push({
        kind: 'member', refId: m.email, displayName: m.displayName, initials,
        tag: '闲置', tagSeverity: 'normal',
        line2,
        time: timeAgo(m.lastSessionAt), severity: 5,
      });
    }
  }

  for (const p of projects) {
    const initials = p.name.slice(0, 2).toUpperCase();
    if (p.busFactorWarning && p.contributors[0]) {
      const top = p.contributors[0];
      items.push({
        kind: 'project', refId: p.name, displayName: p.name, initials,
        tag: '单点依赖', tagSeverity: 'calm',
        line2: `${escapeHtmlEmail(localPart(top.email))} 一人独撑`,
        time: timeAgo(projectLatest(p.name)), severity: 4,
      });
    }
    if (p.state === 'dormant' && p.contributors.length > 0) {
      let line2 = `上次活动已久`;
      const sessions = projectSessionsByName?.get(p.name);
      if (sessions && sessions.length > 0) {
        let latest = sessions[0]!.startTs;
        for (const s of sessions) if (s.startTs > latest) latest = s.startTs;
        const hours = Math.max(0, (now.getTime() - latest.getTime()) / 3_600_000);
        line2 = `上次活动 ${narrativeIdleSince(hours)}`;
      }
      items.push({
        kind: 'project', refId: p.name, displayName: p.name, initials,
        tag: '沉睡', tagSeverity: 'calm',
        line2,
        time: timeAgo(projectLatest(p.name)), severity: 3,
      });
    }
  }

  return foldSameShape(items);
}

// ---------------------------------------------------------------------------
// Leader-narrative helpers (B-main render rewrite)
// ---------------------------------------------------------------------------

/**
 * Pick the file path the member edited most often across their sessions in
 * the current range. Returns `undefined` when no Edit/Write/MultiEdit tool
 * calls fired. Used by `stuck` attention line2 to put a concrete file name
 * in front of the leader instead of an iteration-density number.
 */
function topEditedFile(sessions: ParsedSession[]): string | undefined {
  const counts = new Map<string, number>();
  for (const s of sessions) {
    for (const m of s.messages) {
      for (const tu of m.toolUses) {
        if (tu.name === 'Edit' || tu.name === 'Write' || tu.name === 'MultiEdit') {
          const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
          if (fp) counts.set(fp, (counts.get(fp) ?? 0) + 1);
        }
      }
    }
  }
  let top: string | undefined;
  let topN = 0;
  for (const [path, n] of counts) if (n > topN) { topN = n; top = path; }
  return top;
}

/**
 * Pick the most recent risky-action pattern (if any) detected across the
 * member's sessions. Returns the same string keys as `RiskyAction['pattern']`.
 * Used by `needs_help` line2 to name the actual operation that tripped the
 * detector rather than a percentage failure rate.
 */
function topRiskyPattern(sessions: ParsedSession[]): string | undefined {
  // Match the Bash-pattern detection done by extractRiskyActions but stop at
  // the first match so we avoid a second linear pass per member.
  const PATTERNS: Array<[RegExp, string]> = [
    [/\brm\s+-rf\b/i,         'rm -rf'],
    [/\bgit\s+push\b.*--force/i, 'force push'],
    [/\bgit\s+reset\s+--hard/i, 'reset --hard'],
    [/\bdrop\s+table\b/i,     'drop table'],
  ];
  for (const s of sessions) {
    for (const m of s.messages) {
      for (const tu of m.toolUses) {
        if (tu.name !== 'Bash') continue;
        const cmd = typeof tu.input.command === 'string' ? tu.input.command : '';
        for (const [re, label] of PATTERNS) {
          if (re.test(cmd)) return label;
        }
      }
    }
  }
  return undefined;
}

/** Friendly label for a risky-action pattern key. */
function riskyPatternLabel(pattern: string): string {
  if (pattern === 'rm -rf')         return '强删文件';
  if (pattern === 'force push')     return '强推分支';
  if (pattern === 'reset --hard')   return '硬重置';
  if (pattern === 'drop table')     return '删表';
  return '高风险命令';
}

/** Local-part extractor (no leak of full email to the dashboard reader). */
function localPart(email: string): string {
  const at = email.indexOf('@');
  return at >= 0 ? email.slice(0, at) : email;
}

/**
 * Strip PII from a raw highlight `detail` (typically the Bash command that
 * produced the commit / push / PR) before it hits the JSON wire or HTML.
 * The PII redactor handles emails / absolute paths / secrets / IPs; we also
 * clip stderr suffixes (`2>&1 | tail -N`) and hard-cap length so the
 * dashboard never serves a 500-byte shell pipe.
 */
function redactHighlightDetail(raw: string): string {
  if (!raw) return '';
  let s = redactForLLM(raw);
  // Strip the common "&& git push ... 2>&1 | tail -N" stderr decorator —
  // it's noise on the dashboard, real reviewers can pull it from the raw
  // session if they care.
  s = s.replace(/\s*2>&1\s*\|\s*(tail|head)\s+-?\d*\s*$/u, '');
  s = s.replace(/\s*\|\s*(tail|head)\s+-?\d*\s*$/u, '');
  if (s.length > 120) s = s.slice(0, 117) + '…';
  return s;
}

/**
 * Trim a long absolute path to its last two segments so the dashboard can
 * surface a recognisable filename without the home/cwd noise. Mirrors
 * `shortFile` in `views/_leader-lang.ts`; duplicated here to avoid a
 * leadership/views ↔ leadership/aggregator cycle.
 */
function shortFilePath(path: string): string {
  if (!path) return '';
  const parts = path.replace(/\\/g, '/').split('/').filter(Boolean);
  if (parts.length <= 1) return parts[0] ?? path;
  return parts.slice(-2).join('/');
}

/**
 * Idle-hours → leader-friendly phrase. Mirrors `idleSince` in `_leader-lang.ts`
 * (duplicated to avoid cycle). Used inside the attention `line2` builder.
 */
function narrativeIdleSince(idleHours: number): string {
  if (idleHours < 1) return '刚刚';
  if (idleHours < 4) return `${Math.round(idleHours)} 小时前`;
  if (idleHours < 24) return `今天早些时候`;
  const days = Math.round(idleHours / 24);
  if (days === 1) return '昨天';
  if (days < 7) return `${days} 天前`;
  if (days < 14) return '一周前';
  if (days < 30) return `${Math.floor(days / 7)} 周前`;
  return '一个月以上';
}

/**
 * Collapse same-shape attention rows into a single "N 个X" row, then sort
 * by severity DESC and cap at 10 globally (P-D2). A "shape" is defined by
 * `${kind}:${tag}` — e.g. all "单点依赖" project rows fold together, all
 * "求助" member rows fold together. Groups of 2 or fewer pass through
 * unchanged so small teams don't see N=1 / N=2 fold rows.
 *
 * The folded row picks the worst severity in the group and packs the first
 * three displayNames into `line2` so the leader still sees who is in the
 * fold without expanding. Identical refId is preserved on the sample so a
 * downstream slideover click still works (lands on the first member /
 * project in the fold).
 */
function foldSameShape(items: AttentionItem[]): AttentionItem[] {
  const groups = new Map<string, AttentionItem[]>();
  for (const it of items) {
    const key = `${it.kind}:${it.tag}`;
    const arr = groups.get(key) ?? [];
    arr.push(it);
    groups.set(key, arr);
  }
  const folded: AttentionItem[] = [];
  for (const group of groups.values()) {
    if (group.length <= 2) {
      folded.push(...group);
      continue;
    }
    const sample = group[0]!;
    const preview = group.slice(0, 3).map((g) => g.displayName).join('、');
    const ellipsis = group.length > 3 ? '...' : '';
    folded.push({
      ...sample,
      displayName: `${group.length} 个${sample.tag}`,
      initials: String(group.length),
      line2: preview + ellipsis,
      severity: Math.max(...group.map((g) => g.severity)),
    });
  }
  return folded.sort((a, b) => b.severity - a.severity).slice(0, 10);
}

/**
 * Escape an email for safe embedding in HTML emitted unescaped by the
 * attention renderer. Emails almost never contain `<`/`>`, but a malformed
 * envelope could; we encode `&<>` defensively here so line2 stays trusted.
 */
function escapeHtmlEmail(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildMemberSnapshotInner(
  email: string,
  memberSessions: ParsedSession[],
  allSessions: ParsedSession[],
  teamMedianTokens: number,
  input: BuildOverviewInput,
): MemberSnapshot {
  const display = email.includes('@') ? email.split('@')[0]! : email;
  const activity = computeActivity(memberSessions);
  const cost = computeCostUsd(memberSessions);
  void cost; // available to callers via computeCostUsd; cost included in today below

  // Trend over 7 days (sessions per day, oldest first)
  const trend7d = computeTrend7d(memberSessions, input.now);

  // Past 7d for rhythm delta
  const sevenDayWindowStart = new Date(input.now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const todaySessions = filterToday(memberSessions, input.now);
  const past7Sessions = memberSessions.filter((s) => s.startTs < sevenDayWindowStart);
  const deltaVs7dAvgPct = computeRhythmDelta(todaySessions, past7Sessions);

  // State badge — priority: stuck > needs_help > low_activity > quiet > active
  let stuck = false;
  const cwds = new Set(memberSessions.map((m) => m.envelope.cwd));
  for (const cwd of cwds) {
    const r = detectBlocker(memberSessions, cwd, input.now);
    if (r.isBlocked) { stuck = true; break; }
  }

  const teamAvgWebSearch = avg(allSessions.map((s) => {
    let n = 0;
    for (const m of s.messages) for (const tu of m.toolUses) if (tu.name === 'WebSearch' || tu.name === 'WebFetch') n++;
    return n;
  }));
  const help = detectHelpNeeded(memberSessions, teamAvgWebSearch);
  const slacking = detectLowActivity(
    memberSessions,
    teamMedianTokens,
    { mainProjects: input.mainProjects ?? [] },
  );

  let badge: MemberStateBadge;
  if (stuck) badge = 'stuck';
  else if (help.isNeeded) badge = 'needs_help';
  else if (slacking.isLow) badge = 'low_activity';
  else if (activity.sessions === 0) badge = 'quiet';
  else badge = 'active';

  const warnings: string[] = [];
  const overflow = countContextOverflow(memberSessions);
  if (overflow > 0) warnings.push(sanitizeWarningText(`context 爆炸 ${overflow} 次`));
  const failRate = computeToolFailureRate(memberSessions);
  if (failRate > 0.2) warnings.push(sanitizeWarningText(`tool 失败率 ${(failRate * 100).toFixed(0)}%`));
  const risky = extractRiskyActions(memberSessions);
  if (risky.length > 0) warnings.push(sanitizeWarningText(`危险动作 ${risky.length} 次`));

  // Top project today — use the resolved project identity (owner/repo when
  // a github remote is known, else cwd-derived) so the member's topProject
  // matches the project list rendered on the Overview.
  const projectCounts = new Map<string, number>();
  for (const s of todaySessions) {
    const key = resolveProjectIdentity(s.envelope);
    projectCounts.set(key, (projectCounts.get(key) ?? 0) + 1);
  }
  let topProject: string | undefined;
  let topMax = 0;
  for (const [p, c] of projectCounts) if (c > topMax) { topMax = c; topProject = p; }

  // Last session timestamp — used by deriveAttention to compute real idle hours
  // for low_activity members. Picks the maximum startTs across this member's sessions.
  let lastSessionAt: string | undefined;
  if (memberSessions.length > 0) {
    let latest = memberSessions[0]!.startTs;
    for (const s of memberSessions) if (s.startTs > latest) latest = s.startTs;
    lastSessionAt = latest.toISOString();
  }

  // Pre-compute fields that deriveAttention's line2 strings need so it doesn't
  // have to re-iterate session data per member.
  const iterationDensity = computeIterationDensity(memberSessions);
  let userMsgChars = 0;
  let userMsgCount = 0;
  for (const s of memberSessions) {
    for (const m of s.messages) {
      if (m.role === 'user') {
        userMsgChars += m.text.length;
        userMsgCount += 1;
      }
    }
  }
  const meanPromptLen = userMsgCount === 0 ? 0 : Math.round(userMsgChars / userMsgCount);

  return {
    email,
    displayName: display,
    stateBadge: badge,
    today: {
      sessions: todaySessions.length,
      tokens: todaySessions.reduce((a, s) => a + s.tokens.input + s.tokens.output, 0),
      estMinutes: computeActivity(todaySessions).estMinutes,
      costUsd: computeCostUsd(todaySessions),
    },
    trend7d,
    deltaVs7dAvgPct,
    warnings,
    topProject,
    lastSessionAt,
    toolFailureRate: failRate,
    riskyActionCount: risky.length,
    iterationDensity,
    meanPromptLen,
  };
}

function buildProjectSnapshotInner(name: string, projectSessions: ParsedSession[], now: Date): ProjectSnapshot {
  const state = classifyProject(projectSessions, now);
  const contributors = computeContributors(projectSessions);
  const busFactorWarning = hasBusFactorWarning(contributors);
  const trend7d = computeTrend7d(projectSessions, now);
  const phaseGuess = guessPhase(projectSessions);
  const healthScore = computeHealthScore(projectSessions);
  const eta = projectEta(projectSessions, now);

  // Active-today ratio = (contributors with ≥1 session in last 24h) / total contributors.
  // Replaces the placeholder "sum(trend7d) / recentFiles" heuristic in the
  // project row's progress bar.
  const todayProjectSessions = filterToday(projectSessions, now);
  const activeToday = new Set<string>();
  for (const s of todayProjectSessions) activeToday.add(s.envelope.userId);
  const activeTodayCount = activeToday.size;
  const activeTodayPct = contributors.length === 0
    ? 0
    : Math.round((activeTodayCount / contributors.length) * 1000) / 1000;

  // Most-recently edited file across this project's sessions, with the
  // user who fired the Edit/Write/MultiEdit tool call and the message
  // timestamp. Drives the "最近: <file> (<author> · <时间>)" narrative line
  // on the Overview project row. Walks newest-session-first and returns at
  // the first edit tool found so we don't iterate the whole project body.
  let lastTouch: { filePath: string; by: string; ts: string } | undefined;
  const sorted = projectSessions.slice().sort((a, b) => b.startTs.getTime() - a.startTs.getTime());
  outer: for (const s of sorted) {
    for (let i = s.messages.length - 1; i >= 0; i--) {
      const m = s.messages[i]!;
      for (let j = m.toolUses.length - 1; j >= 0; j--) {
        const tu = m.toolUses[j]!;
        if (tu.name === 'Edit' || tu.name === 'Write' || tu.name === 'MultiEdit') {
          const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
          if (fp) {
            lastTouch = {
              filePath: fp,
              by: s.envelope.userId,
              ts: (m.ts ?? s.startTs).toISOString(),
            };
            break outer;
          }
        }
      }
    }
  }

  return {
    name,
    state,
    contributors,
    busFactorWarning,
    trend7d,
    phaseGuess,
    healthScore,
    etaDays: eta.etaDays,
    etaConfidence: eta.confidence,
    activeTodayPct,
    activeTodayCount,
    ...(lastTouch ? { lastTouch } : {}),
  };
}

export function buildMemberDetail(input: {
  collectorDir: string;
  email: string;
  range: DateRange;
  now: Date;
  sessions?: ParsedSession[];
  mainProjects?: string[];
}): (MemberSnapshot & { detail: MemberDetail }) | null {
  const all = input.sessions ?? loadSessionsForRange(input.collectorDir, input.range);
  if (input.sessions) propagateRemotes(all);
  const inRange = all.filter((s) => s.startTs >= input.range.start && s.startTs <= input.range.end);
  const memberSessions = inRange.filter((s) => s.envelope.userId === input.email);
  if (memberSessions.length === 0) return null;

  const teamMedianTokens = median(inRange.map((s) => s.tokens.input + s.tokens.output));
  const base = buildMemberSnapshotInner(input.email, memberSessions, inRange, teamMedianTokens, {
    collectorDir: input.collectorDir,
    range: input.range,
    now: input.now,
    mainProjects: input.mainProjects,
  });

  // Detail-only fields
  const toolFailureRate = computeToolFailureRate(memberSessions);
  const overContext200kCount = countContextOverflow(memberSessions);
  const iterationDensity = computeIterationDensity(memberSessions);
  const riskyActions = extractRiskyActions(memberSessions);
  const modelMix = computeModelMix(memberSessions);
  const webResearchCount = computeWebResearch(memberSessions);

  // P-A1: previously-unused signals now wired into the snapshot.
  const todayMemberSessions = filterToday(memberSessions, input.now);
  const focus = computeFocus(todayMemberSessions);
  const prLenSeries = promptLengthSeries(memberSessions);
  // "Historical" = same member's sessions in the 7-day window preceding range.start.
  const historyWindowMs = 7 * 24 * 60 * 60 * 1000;
  const historicalStart = new Date(input.range.start.getTime() - historyWindowMs);
  const historicalMemberSessions = all.filter(
    (s) =>
      s.envelope.userId === input.email &&
      s.startTs >= historicalStart &&
      s.startTs < input.range.start,
  );
  const newSurfaceCount = computeNewSurfaceCount(memberSessions, historicalMemberSessions);

  // Collaborators — files shared with others via collab hits
  const collabHits = detectCollabHits(inRange);
  const collaborators = new Map<string, Set<string>>();
  for (const h of collabHits) {
    if (!h.members.includes(input.email)) continue;
    for (const other of h.members) {
      if (other === input.email) continue;
      const set = collaborators.get(other) ?? new Set<string>();
      set.add(h.filePath);
      collaborators.set(other, set);
    }
  }

  // Sessions list with 200-char preview
  const sessionsList: SessionSummary[] = memberSessions
    .slice()
    .sort((a, b) => b.startTs.getTime() - a.startTs.getTime())
    .map((s): SessionSummary => {
      const firstUser = s.messages.find(
        (m) => m.role === 'user' && m.text.trim().length > 0 && !isSystemInjectedUserMessage(m.text),
      );
      const text = firstUser?.text ?? '';
      // P-A3: enumerate up to the first 12 non-empty user prompts. We
      // intentionally cap at 12 and drop the `.full` payload here because
      // a single member endpoint was shipping 1.1 MB on real data — the
      // slide-over only renders 6 rows anyway. Clients needing the full
      // session text should hit the raw session via the `Browse` tab.
      // (Reviewer-flagged 2026-05-18 launch audit P0.)
      const PROMPT_CAP = 12;
      const PROMPT_PREVIEW_BYTES = 200;
      const allPrompts = s.messages
        .filter((m) => m.role === 'user' && m.text.trim().length > 0 && !isSystemInjectedUserMessage(m.text))
        .slice(0, PROMPT_CAP)
        .map((m) => ({
          ts: (m.ts ?? s.startTs).toISOString(),
          preview:
            m.text.length > PROMPT_PREVIEW_BYTES
              ? m.text.slice(0, PROMPT_PREVIEW_BYTES)
              : m.text,
          // `full` retained at 1× the preview budget so the UI can show a
          // slightly longer expanded view without re-fetching, but we no
          // longer carry tens of KB per prompt.
          full: m.text.length > 800 ? m.text.slice(0, 800) + '…' : m.text,
        }));
      return {
        sessionId: s.envelope.sessionId,
        capturedAt: s.envelope.capturedAt,
        projectName: resolveProjectIdentity(s.envelope),
        totalTokens: s.tokens.input + s.tokens.output,
        firstPromptPreview: text.length > PROMPT_PREVIEW_BYTES ? text.slice(0, PROMPT_PREVIEW_BYTES) : text,
        // The full first prompt is the one place a leader might really
        // want to read the original input verbatim; preserve it untruncated.
        firstPromptFull: text,
        allPrompts,
      };
    });

  // Heatmap + top files
  const heatmap7x24 = computeHeatmap7x24(memberSessions, input.now);
  const fileEdits = new Map<string, number>();
  for (const s of memberSessions) {
    for (const m of s.messages) {
      for (const tu of m.toolUses) {
        if (['Edit', 'Write', 'MultiEdit'].includes(tu.name)) {
          const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
          if (fp) fileEdits.set(fp, (fileEdits.get(fp) ?? 0) + 1);
        }
      }
    }
  }
  const topFiles = [...fileEdits.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([path, edits]) => ({ path, edits }));

  const detail: MemberDetail = {
    toolFailureRate,
    overContext200kCount,
    iterationDensity,
    riskyActions,
    collaborators: [...collaborators.entries()].map(([withEmail, files]) => ({
      withEmail,
      sharedFiles: [...files],
    })),
    modelMix,
    webResearchCount,
    sessions: sessionsList,
    heatmap7x24,
    topFiles,
    focus,
    promptLengthSeries: prLenSeries,
    newSurfaceCount,
  };

  return { ...base, detail };
}

export function buildProjectDetail(input: {
  collectorDir: string;
  projectName: string;
  range: DateRange;
  now: Date;
  sessions?: ParsedSession[];
}): (ProjectSnapshot & { detail: ProjectDetail }) | null {
  const all = input.sessions ?? loadSessionsForRange(input.collectorDir, input.range);
  if (input.sessions) propagateRemotes(all);
  const inRange = all.filter((s) => s.startTs >= input.range.start && s.startTs <= input.range.end);
  const projectSessions = inRange.filter(
    (s) => resolveProjectIdentity(s.envelope) === input.projectName,
  );
  if (projectSessions.length === 0) return null;

  const base = buildProjectSnapshotInner(input.projectName, projectSessions, input.now);

  const todayFiles = getRecentFiles(filterToday(projectSessions, input.now));
  const weekFiles = getRecentFiles(projectSessions);
  const extensionMix = computeExtensionMix(projectSessions);
  const testRatio = computeTestRatio(projectSessions);
  const milestones = extractMilestones(projectSessions);
  const webResearchShare = computeWebResearchShare(projectSessions);
  const heatmap7x24 = computeHeatmap7x24(projectSessions, input.now);

  const fileEdits = new Map<string, number>();
  for (const s of projectSessions) {
    for (const m of s.messages) {
      for (const tu of m.toolUses) {
        if (['Edit', 'Write', 'MultiEdit'].includes(tu.name)) {
          const fp = typeof tu.input.file_path === 'string' ? tu.input.file_path : undefined;
          if (fp) fileEdits.set(fp, (fileEdits.get(fp) ?? 0) + 1);
        }
      }
    }
  }
  const recentFiles = [...fileEdits.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([path, touches]) => ({ path, touches }));

  const collabDensity = computeCollabDensity(projectSessions);

  // 2026-05-18 round-16 audit P0: the slideover's "prompt 的演变 · 看他都在
  // 问什么" section read milestones (raw git commands) on the project drawer,
  // which neither matched the label nor was useful. Surface the real user
  // prompts from sessions touching this project — same filter as the member
  // drawer so slash-command / skill-load noise stays out.
  const PROJECT_PROMPT_CAP = 20;
  const PROJECT_PROMPT_PREVIEW = 200;
  const promptBuckets: { ts: Date; by: string; preview: string }[] = [];
  for (const s of projectSessions) {
    for (const m of s.messages) {
      if (m.role !== 'user') continue;
      if (!m.text || m.text.trim().length === 0) continue;
      if (isSystemInjectedUserMessage(m.text)) continue;
      const ts = m.ts ?? s.startTs;
      const preview = m.text.length > PROJECT_PROMPT_PREVIEW
        ? m.text.slice(0, PROJECT_PROMPT_PREVIEW)
        : m.text;
      promptBuckets.push({ ts, by: s.envelope.userId, preview });
    }
  }
  promptBuckets.sort((a, b) => b.ts.getTime() - a.ts.getTime());
  const recentPrompts = promptBuckets
    .slice(0, PROJECT_PROMPT_CAP)
    .map((p) => ({ ts: p.ts.toISOString(), by: p.by, preview: p.preview }));

  const detail: ProjectDetail = {
    todayFiles,
    weekFiles,
    extensionMix,
    testRatio,
    milestones,
    webResearchShare,
    heatmap7x24,
    recentFiles,
    collabDensity,
    recentPrompts,
  };

  return { ...base, detail };
}

// ----- helpers -----

function loadSessionsForRange(collectorDir: string, range: DateRange): ParsedSession[] {
  return scanAllSessions(collectorDir, {
    fromDate: range.start.toISOString().slice(0, 10),
    toDate: range.end.toISOString().slice(0, 10),
  });
}

function groupBy<T, K>(items: T[], keyFn: (x: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const it of items) {
    const k = keyFn(it);
    const arr = m.get(k) ?? [];
    arr.push(it);
    m.set(k, arr);
  }
  return m;
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  if (sorted.length % 2 === 0) return (sorted[mid - 1]! + sorted[mid]!) / 2;
  return sorted[mid]!;
}

function avg(values: number[]): number {
  if (values.length === 0) return 0;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

function filterToday(sessions: ParsedSession[], now: Date): ParsedSession[] {
  const dayMs = 24 * 60 * 60 * 1000;
  const todayStart = new Date(now.getTime() - dayMs);
  return sessions.filter((s) => s.startTs >= todayStart && s.startTs <= now);
}

// ---------------------------------------------------------------------------
// Encoding sanitisation boundary (P-D2)
// ---------------------------------------------------------------------------

/**
 * Strip lone surrogate code points from a warning string before it enters
 * the snapshot.
 *
 * Context: the on-the-wire `/api/overview` payload is clean UTF-8 — the
 * mojibake the leadership audit observed (`镉遍橳铔ㄤ綔 92 婘\udca1`) was a
 * downstream display issue (a terminal interpreting UTF-8 bytes as GBK).
 * The trailing `\udca1` in that audit copy IS a real signal: it is a lone
 * low surrogate that survived a Buffer-decode somewhere upstream and would
 * have re-corrupted any JSON serializer.
 *
 * We replace lone surrogates with `?` at the construction site so even if
 * upstream transcript bytes ever land mis-decoded, the warning string the
 * dashboard sees stays valid UTF-16 and round-trips cleanly through
 * JSON.stringify → JSON.parse on the client. Well-formed strings pass
 * through unchanged.
 */
export function sanitizeWarningText(s: string): string {
  // Match high surrogate not followed by low, OR low surrogate not preceded
  // by high. The negative-lookaround pair makes the regex idempotent.
  return s.replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g, '?');
}
